### ISSUE TITLE
:quit causes RuntimeException

### ISSUE THREAD

**Issue by gyscos** [albertlatacz/java-repl#117]
```
java> :quit
Exception in thread "main" java.lang.RuntimeException: { expected, j encountered.
	at javarepl.internal.totallylazy.parser.Failure.exception(Failure.java:76)
	at javarepl.internal.totallylazy.parser.Failure.value(Failure.java:72)
	at javarepl.internal.totallylazy.json.Json.map(Json.java:20)
	at javarepl.client.JavaREPLClient.execute(JavaREPLClient.java:72)
	at javarepl.Main.main(Main.java:66)
```

**Comment by gyscos** [comment]
Seems to be because the client receives the following response instead of valid JSON:

```
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:781)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at javarepl.internal.utterlyidle.Status.status(Status.java:81)
	at javarepl.internal.utterlyidle.handlers.ClientHttpHandler.sendHttpRequest(ClientHttpHandler.java:197)
	at javarepl.internal.utterlyidle.handlers.ClientHttpHandler.handle(ClientHttpHandler.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javarepl.internal.totallylazy.reflection.Methods.invoke(Methods.java:91)
	at javarepl.internal.totallylazy.reflection.Methods.lambda$invokeOn$92(Methods.java:98)
	at javarepl.internal.totallylazy.functions.Functions.call(Functions.java:47)
	at javarepl.internal.totallylazy.Callers.call(Callers.java:91)
	at javarepl.internal.totallylazy.Some.map(Some.java:74)
	at javarepl.internal.totallylazy.Dispatcher.invokeOption(Dispatcher.java:71)
	at javarepl.internal.totallylazy.multi.methodOption(multi.java:44)
	at javarepl.internal.utterlyidle.handlers.ClientHttpHandler.handle(ClientHttpHandler.java:145)
	at javarepl.internal.utterlyidle.handlers.ClientHttpHandler.handle(ClientHttpHandler.java:131)
	at javarepl.client.JavaREPLClient.execute(JavaREPLClient.java:67)
	at javarepl.Main.main(Main.java:66)
```
