### ISSUE TITLE
NumberFormatException at startup

### ISSUE THREAD

**Issue by gyscos** [albertlatacz/java-repl#122]
When running, I get an error immediately (it doesn't crash though, and I can keep using the repl):

```
$ javarepl
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at javarepl.internal.jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at javarepl.internal.jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at javarepl.internal.jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at javarepl.internal.jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javarepl.internal.jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at javarepl.internal.jline.TerminalFactory.create(TerminalFactory.java:102)
	at javarepl.internal.jline.TerminalFactory.get(TerminalFactory.java:186)
	at javarepl.internal.jline.TerminalFactory.get(TerminalFactory.java:192)
	at javarepl.internal.jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at javarepl.internal.jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at javarepl.internal.jline.console.ConsoleReader.<init>(ConsoleReader.java:227)
	at javarepl.Main.main(Main.java:55)

Welcome to JavaREPL version dev (OpenJDK 64-Bit Server VM, Java 1.8.0_144)
Type expression to evaluate, :help for more options or press tab to auto-complete.
Connected to local instance at http://localhost:36193
java> 
```

**Comment by pkhamutou** [comment]
try
```bash
export TERM=xterm-color
```
