### ISSUE TITLE
Build Failure in Win10

### ISSUE THREAD

**Issue by shw5258** [albertlatacz/java-repl#94]
I couldn't setup dependencies . somehow the folder does not have 'unzip' program I may need unzip file.
`C:\java-repl-master>ant
Buildfile: C:\java-repl-master\build.xml

build:

clean:

update:
    [mkdir] Created dir: C:\java-repl-master\lib\build
    [mkdir] Created dir: C:\java-repl-master\lib\packaged
    [mkdir] Created dir: C:\java-repl-master\lib\optional
    [mkdir] Created dir: C:\java-repl-master\lib\runtime
     [java] Downloading http://repo1.maven.org/maven2/jline/jline/2.12/jline-2.12.jar (mvn:jline:jline:jar:2.12)
     [java] Downloading http://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar (mvn:org.hamcrest:hamcrest-core:jar:1.3)
     [java] Downloading http://repo1.maven.org/maven2/cglib/cglib/3.1/cglib-3.1.jar (mvn:cglib:cglib:jar:3.1)
     [java] Downloading http://repo1.maven.org/maven2/junit/junit-dep/4.8.2/junit-dep-4.8.2.jar (mvn:junit:junit-dep:jar:4.8.2)
     [java] Downloading http://repo1.maven.org/maven2/org/ow2/asm/asm-all/4.2/asm-all-4.2.jar (mvn:org.ow2.asm:asm-all:jar|sources:4.2)
     [java] Downloading http://repo1.maven.org/maven2/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar (mvn:org.hamcrest:hamcrest-library:jar:1.3)
     [java] Downloading http://repo1.maven.org/maven2/org/ow2/asm/asm-all/4.2/asm-all-4.2-sources.jar (mvn:org.ow2.asm:asm-all:jar|sources:4.2)
     [java] Downloading http://jarjar.googlecode.com/files/jarjar-1.1.jar
     [java] Downloading http://repo1.maven.org/maven2/org/objenesis/objenesis/2.1/objenesis-2.1.jar (mvn:org.objenesis:objenesis:jar:2.1)
     [java] Downloading http://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar (mvn:antlr:antlr:jar:2.7.7)
     [java] Downloading http://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1-sources.jar (mvn:org.antlr:stringtemplate:jar|sources:3.2.1)
     [java] Downloading http://repo.bodar.com/com/googlecode/totallylazy/totallylazy/1193/totallylazy-1193.jar (mvn://repo.bodar.com/com.googlecode.totallylazy:totallylazy:jar|sources:1193)
     [java] Downloading http://repo.bodar.com/com/googlecode/funclate/funclate/131/funclate-131-sources.jar (mvn://repo.bodar.com/com.googlecode.funclate:funclate:jar|sources:131)
     [java] Downloading http://repo.bodar.com/com/googlecode/utterlyidle/utterlyidle/742/utterlyidle-742.jar (mvn://repo.bodar.com/com.googlecode.utterlyidle:utterlyidle:jar|sources:742)
     [java] Downloading http://repo.bodar.com/com/googlecode/funclate/funclate/131/funclate-131.jar (mvn://repo.bodar.com/com.googlecode.funclate:funclate:jar|sources:131)
     [java] Downloading http://repo.bodar.com/com/googlecode/utterlyidle/utterlyidle/742/utterlyidle-742-sources.jar (mvn://repo.bodar.com/com.googlecode.utterlyidle:utterlyidle:jar|sources:742)
     [java] Downloading http://repo.bodar.com/com/googlecode/yadic/yadic/171/yadic-171.jar (mvn://repo.bodar.com/com.googlecode.yadic:yadic:jar|sources:171)
     [java] Downloading http://repo.bodar.com/com/googlecode/yadic/yadic/171/yadic-171-sources.jar (mvn://repo.bodar.com/com.googlecode.yadic:yadic:jar|sources:171)
     [java] Downloading http://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar (mvn:org.antlr:stringtemplate:jar|sources:3.2.1)
     [java] Downloading http://repo.bodar.com/com/googlecode/totallylazy/totallylazy/1193/totallylazy-1193-sources.jar (mvn://repo.bodar.com/com.googlecode.totallylazy:totallylazy:jar|sources:1193)

compile:

BUILD FAILED
C:\java-repl-master\build.xml:195: The following error occurred while executing this line:
C:\java-repl-master\build.xml:98: Execute failed: java.io.IOException: Cannot run program "unzip": CreateProcess error=2, 지정된 파일을 찾을 수 없습니다
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: CreateProcess error=2, 지정된 파일을 찾을 수 없습니다
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 36 more

Total time: 51 seconds

C:\java-repl-master>ant -version
Apache Ant(TM) version 1.9.6 compiled on June 29 2015`

**Comment by albertlatacz** [comment]
Unfortunately it was not tested/designed for building on Windows.
